title: toli.love
description: Toli's Love Bounty

remote_theme: mmistakes/minimal-mistakes

plugins:
- jekyll-remote-theme 
- jekyll-include-cache
- gemfile

minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"